Repository MasterChatCenter/backend, pull requests merged in 2020-12, with the labels that each got.

#32 Hotfix/create new companies
  api/.env.example
  api/README.md
  api/package-lock.json
  api/package.json
  api/src/controllers/company.js
  api/src/controllers/user.js
  api/src/index.js
  api/src/services/message.js
  api/src/services/user.js
  api/src/utils/debug.js
  webhook/task.py
Labels: bug

#33 Bugfix/conversation creation
  .gitignore
  api/src/controllers/conversation.js
  api/src/services/conversation.js
  api/src/services/message.js
  api/src/services/user.js
Labels: Backend, bug

#37 Conversations query by user_id
  api/src/controllers/conversation.js
  api/src/routes/conversation.js
  api/src/services/conversation.js
  api/src/services/user.js
Labels: Backend

#38 Feature/change database
  api/src/controllers/company.js
  api/src/controllers/message.js
  api/src/controllers/user.js
  api/src/index.js
  api/src/routes/router.js
  api/src/sequelizer/index.js
  api/src/sequelizer/models/company.model.js
  api/src/sequelizer/models/conversation.model.js
  api/src/sequelizer/models/customer.model.js
  api/src/sequelizer/models/message.model.js
  api/src/sequelizer/models/user.model.js
  api/src/sequelizer/relationSetup.js
  api/src/services/conversation.js
  api/src/services/customer.js
  api/src/services/message.js
  api/src/services/user.js
  api/src/utils/utils.js
  docker-compose.prod.yml
  docker-compose.yml
Labels: enhancement

#40 Feat: update socket
  api/package-lock.json
  api/package.json
  api/src/index.js
  api/src/sequelizer/index.js
  api/src/services/message.js
  api/src/socket/handlers.js
  api/src/socket/index.js
  webhook/task.py
  websocket/server.py
Labels: Backend
